### ISSUE TITLE
gtk3-widget-factory got Gtk-Warning

### ISSUE THREAD

**Issue by wangxa** [system76/pop-gtk-theme#11]
**Reporter info**

```
 * Distribution - Fedora
 * Gtk+ 3.0 version - 3.24
 * Desktop environment - Gnome
 * Pop version - 2.0.5r1
 ```

**Related Application and/or Shell theming (or name of widget)**
gtk3-widget-factory

**Actual issue**
`
(gtk3-widget-factory:5682): Gtk-WARNING **: Theme parsing error: gtk.css:1:0: unknown @ rule
`
`
(gtk3-widget-factory:5682): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
`

**Steps to reproduce**

**Expected behavior**

**Behavior in Adwaita**
No such warning information

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Can you tell what widget is throwing the error? Opening it up on my end I don't see any widgets that are failing to load.

**Comment by wangxa** [comment]
If I am running `gvim`, the error message is:
`(gvim:8658): Gtk-WARNING **: Theme parsing error: gtk.css:1:0: unknown @ rule`

![screenshot from 2017-08-23 12-39-49](https://user-images.githubusercontent.com/1250269/29613981-437a9022-8800-11e7-9153-1f40cf31a1d9.png)

If `gtk3-widget-factory` is executed, the error message is:

![screenshot from 2017-08-23 12-42-14](https://user-images.githubusercontent.com/1250269/29614045-8a752ae6-8800-11e7-9b2e-a4f57f5bedfa.png)


`pop-gtk-theme`: `2.0.5r1`
`gnome-shell`: `3.24.3`
`gtk3`: `3.22.18`
`gjs`: `1.48.6`

**Comment by wangxa** [comment]
After update to version `2.0.6`,

The warning message of `Theme parsing error: gtk.css:1:0: unknown @ rule` disappears. But the another warning is still there.

**Comment by wangxa** [comment]
Do you think this message is related to the `gtk.gresouce`?

I found the way to show the message in gvim.

From gnome-terminal, run `gvim`, and then click the `search and replace` button in the menu bar, then the message will appear. It seems gdk-pixbuf has problem to load the checkbox or radiobox PNG icons.

**Comment by isantop** [comment]
The error message would indicate that it can't load the images for some widget, but it's not a very helpful error because it doesn't tell anyone what widget it's trying to load. Images for the checkboxes and radio buttons are included in the theme, so there isn't any reason for it not to load those. There must be a different widget that is having problems, however I can't tell what that widget is.

**Comment by ErikWallstrom** [comment]
I also have this problem. Uncommenting `@charset "UTF-8";` in `gtk.css` removed the warning

**Comment by isantop** [comment]
That's a separate issue that is fixed in 2.0.6

**Comment by wangxa** [comment]
I use GTK3 inspector to trace the CSS used in `gvim` when the search tool button is click:
```bash
  $ GTK_DEBUG=interactive gvim
```
Finally, I found the line  2501 in `gtk.css` (Pop-dark theme, gtk-3.22):
```css
check:checked {
  -gtk-icon-source: image(-gtk-recolor(url("assets/scalable/checkbox-checked-symbolic.svg")), -gtk-recolor(url("assets/scalable/checkbox-checked-symbolic.symbolic.png")));
}
```
The second icon `assets/scalable/checkbox-checked-symbolic.symbolic.png` in the image fallback doesn't exist. Do you think this is the problem? 

In runtime, the SVG image is converted into a base64-encode image specification with the MIME `image/png`. Maybe this specification causes the issue.

![screenshot from 2017-08-23 21-44-24](https://user-images.githubusercontent.com/1250269/29637544-58b74c5e-884c-11e7-91f3-80df116e5262.png)

**Comment by isantop** [comment]
I have corrected the typo creating that line in the .css as of e163301, however the problem still happens, so I don't think that was the source of the problem.

**Comment by wangxa** [comment]
I think this issue is caused by the non-existence of the second icon in the image fallback. For example, `checkbox-unchecked-symbolic.png` doesn't exist, so gdk-pixbuf will throw warning when it is checking all icons in the `-gtk-icon-source`'s image fallback and meets the non-existent file.

**Comment by rmkc23** [comment]
I get the same message running the demo at:
https://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html

(stackdemo.py:13242): Gtk-WARNING **: 16:24:23.935: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.

I'm running this using the PyCharm IDE on a Mac (brew install pygobject3 --with-python@2 gtk+3)

**Comment by heartofrainbow** [comment]
For Mac users encountering this warning, just install adwaita-icon-theme using homebrew. (brew install adwaita-icon-theme)

That fixes the warning.
Verified on macOS Mojave 10.14.3.

**Comment by jaimet** [comment]
I appreciate that this issue discusses what might be *at least* 3 distinct bugs (possibly more):

1. `Theme parsing error`
2. `Could not load a pixbuf from icon theme.`
3. `Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.`

I've just worked through fixing the *third* type (`.../bullet-symbolic.svg`) and although I'm running debian stable and testing (buster and bullseye) instead of pop-os, I'm adding this comment in case it helps anyone here.

GTK applications need the svg gdk-pixbuf loader (`/usr/lib/<arch>/gdk-pixbuf-2.0/<ver>/loaders/libpixbufloader-svg.so`) installed in order to be able to load svg images but, due to package dependency changes back in 2006, it's possible that the package that contains the svg gdk-pixbuf loader (that's the `librsvg2-common` package) is not automatically installed (I've managed to get 2 full debian gtk-based gui systems up-and-running *without* `librsvg2-common` being automatically pulled-in as an install-time dependency). What then happens is that you get weird gtk3 theme bugs that are difficult to track down (svg images used for things like scrollbar buttons just don't appear, and buttons that normally have svg borders don't get any borders around them at all which makes it difficult to realise that they are buttons) and when you start gtk applications (such as `gtk3-widget-factory`) from the command line, you get error messages such as `Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg. This may indicate that pixbuf loaders or the mime database could not be found.`

I don't know how your package manager works here in pop-os, but if you get an error message about not being to load a pixbuf from an svg file, then please make sure you have the `librsvg2-common` package installed.

I'll update this comment with a reference to the debian bts bug report once I've reported it.

Hth, j

**Comment by meiyujack** [comment]
> I appreciate that this issue discusses what might be _at least_ 3 distinct bugs (possibly more):
> 
>     1. `Theme parsing error`
> 
>     2. `Could not load a pixbuf from icon theme.`
> 
>     3. `Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg.`
> 
> 
> I've just worked through fixing the _third_ type (`.../bullet-symbolic.svg`) and although I'm running debian stable and testing (buster and bullseye) instead of pop-os, I'm adding this comment in case it helps anyone here.
> 
> GTK applications need the svg gdk-pixbuf loader (`/usr/lib/<arch>/gdk-pixbuf-2.0/<ver>/loaders/libpixbufloader-svg.so`) installed in order to be able to load svg images but, due to package dependency changes back in 2006, it's possible that the package that contains the svg gdk-pixbuf loader (that's the `librsvg2-common` package) is not automatically installed (I've managed to get 2 full debian gtk-based gui systems up-and-running _without_ `librsvg2-common` being automatically pulled-in as an install-time dependency). What then happens is that you get weird gtk3 theme bugs that are difficult to track down (svg images used for things like scrollbar buttons just don't appear, and buttons that normally have svg borders don't get any borders around them at all which makes it difficult to realise that they are buttons) and when you start gtk applications (such as `gtk3-widget-factory`) from the command line, you get error messages such as `Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/bullet-symbolic.svg. This may indicate that pixbuf loaders or the mime database could not be found.`
> 
> I don't know how your package manager works here in pop-os, but if you get an error message about not being to load a pixbuf from an svg file, then please make sure you have the `librsvg2-common` package installed.
> 
> I'll update this comment with a reference to the debian bts bug report once I've reported it.
> 
> Hth, j

Still have problem. My OS is Pop 20.04 and already have installed librsvg2-common.
My situation is like your second one.
(io.elementary.appcenter:2919): Gtk-WARNING **: 11:49:54.509: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.

** (io.elementary.appcenter:2919): CRITICAL **: 11:58:47.294: PackageKitBackend.vala:462: 操作被取消

** (io.elementary.appcenter:2919): CRITICAL **: 11:58:47.294: gee_abstract_collection_iterator: assertion 'self != NULL' failed

** (io.elementary.appcenter:2919): CRITICAL **: 11:58:47.294: gee_iterator_next: assertion 'self != NULL' failed

** (io.elementary.appcenter:2919): WARNING **: 11:58:59.479: FlatpakBackend.vala:478: Unable to update appstream: While pulling appstream2/x86_64 from remote flathub: opcode set-read-source: Opening content object 6f7c1253dea25a3e4008725c9b163a83c3bc32e53aa9dd8fe423e72256bad873: Couldn't find file object '6f7c1253dea25a3e4008725c9b163a83c3bc32e53aa9dd8fe423e72256bad873'
What I've done:
sudo apt upgrade && sudo apt update && sudo apt install --reinstall librsvg2-common
The Pop Shop can't work especially in main page and no responding
