### ISSUE TITLE
Inkscape toolbars unusable

### ISSUE THREAD

**Issue by caneta** [system76/pop-gtk-theme#33]
**Reporter info**
```
 * Ubuntu 17.04 Zesty
 * Gtk+ 3.0 version - 3.22.11-0ubuntu3
 * Desktop environment - Gnome with Unity
 ```
**Pop version**
system76-pop-gtk-theme version 1.3.1.6

**Other theme stuff installed**
* system76-wallpapers - System76 Wallpapers
* system76-pop-theme - System76 Pop Theme Metapackage
* system76-pop-fonts - System76 Pop Fonts
* system76-pop-icon-theme - System76 Pop Icons
* system76-pop-gtk-theme - System76 Pop GTK Theme
* plymouth-theme-system76-logo - graphical boot animation and logger - system76-logo theme
* plymouth-theme-system76-text - graphical boot animation and logger - system76-text theme
* system76-default-settings - default settings for the System76 desktop
* system76-desktop - System76 Desktop Metapackage

**Related Application and/or Shell theming (or name of widget)**
Inkscape

**Actual issue**
The Inkscape toolbars are unusable due to their color and background. See the image below:
![inkscape](https://user-images.githubusercontent.com/4066659/27261681-49edf714-5448-11e7-85e7-b84e61d91138.png)

**Steps to reproduce (if you knew)**
Just open the program Inkscape

**Expected behaviour**
To see properly every toolbar in order to work. Is it normal to have some orange icons and no different color on mouse hover like in other gtk based programs?

Thank you

**Comment by isantop** [comment]
This is actually caused by some bugs with Inkscape unfortunately. Inkscape uses flat buttons for toolbar items, which don't have a hover color or difference between hover states and normal states.

Orange buttons are currently active things (the current tool, select; the active snapping modes; etc.)

Inkscape also doesn't specify symbolic icons for the toolbars, which prevents them being automatically colored using GTK. If they were set up as symbolic icons, then they would correctly recolor to be darker and thus more visible on light-background toolbars. As it stands, the colors of the icons can't be changed without breaking this ability in most other apps.

**Comment by ryanleesipes** [comment]
So the proper resolution here would be to file this against Inkscape @caneta - that way they can bring this inline with other applications.

**Comment by isantop** [comment]
@caneta I'll also add that as a workaround, you can install the GTK3 development version of Inkscape. It's actually quite stable and works pretty well. Then, launch Inkscape with `GTK_THEME=Pop-Dark inkscape`. This will tell Inkscape to use the dark theme instead of the light theme, which makes the icons much more visible. You can make this automatic by running `cp /usr/share/applications/inkscape.desktop ~/.local/share/applications`, then adding the `GTK_THEME=Pop-Dark` item to the `Exec=` line in `~/.local/share/applications/inkscape.desktop`.

**Comment by caneta** [comment]
Ok guys, thank you!
