### ISSUE TITLE
Text on Unity sound menu is too light for Spotify

### ISSUE THREAD

**Issue by sayakbiswas** [system76/pop-gtk-theme#41]
**Reporter info**

```
 * Distribution - Ubuntu 16.04.2 LTS
 * Gtk+ 3.0 version - 3.18.9-1ubuntu3.3
 * Desktop environment - Unity
 * Pop version - 1.0.8
 ```

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
The text on the sound menu with the Now Playing information in Unity is too light, almost unreadable. This is only with the Spotify sound menu, rhythmbox seems to be fine.

**Steps to reproduce (if you knew)**
Have the pop theme active. Launch Spotify and play a song. The text showing the song information is very light gray which makes it very hard to read.
![screenshot from 2017-06-23 20-13-14](https://user-images.githubusercontent.com/315187/27504045-7cf1bc38-5851-11e7-8937-c79277ffe8a0.png)

**Expected behaviour**
The text should be black.

**Behaviour in Adwaita**

**Other Note (feature-request, question, etc...)**

**Comment by isantop** [comment]
Since this doesn't happen with other media players in the menu, I think this appears to be a problem with Spotify manually coding in the color for the text, instead of letting the theme do it automatically. As such, I don't think that this can be fixed in theming. 

As a side note, version 1.0.8 is a bit outdated, and you should consider upgrading to the latest version! The best way is to add the `ppa:system76/pop` repository to your system, which will enable you to get automatic updates. We also offer .deb files for download on the [releases page](https://github.com/system76/pop-gtk-theme/releases) which can be installed on your system.

**Comment by sayakbiswas** [comment]
Hi @isantop 

Yes maybe it is a problem with Spotify. I do think that the icons for the speaker volume and microphone in the popup menu could be darker. I compiled the latest theme after the ppa didn't work. I noticed that those two icons have become lighter still. You can compare the screenshot below with the one I provided earlier.

![screenshot from 2017-06-28 20-03-01](https://user-images.githubusercontent.com/315187/27665740-f9ac8dea-5c3c-11e7-9c20-05add415efa1.png)
