### ISSUE TITLE
Not able to add the System76 POP repositery in Ubuntu 16.04.2?

### ISSUE THREAD

**Issue by rdkumarj** [system76/pop-gtk-theme#43]
Hi 

I am using Below version of Ubuntu and could not add the POP repository as per the attached screen shot. Please look into it.

VERSION="16.04.2 LTS (Xenial Xerus)"

![pop issue](https://user-images.githubusercontent.com/2478043/27603584-25537390-5b94-11e7-92c9-504d4fc9a1c5.jpg)

Thanks
RD

**Comment by isantop** [comment]
Pop is not currently built for Ubuntu 16.04 due to its usage of GTK+ 3.18, which requires extra support and lots of extra build resources. The team is currently looking into infrastructural changes to help make this work, but in the meantime you can install the latest version of Pop_GTK by getting the source code and building it manually (this will add in support for 3.18 automatically if you do it on 16.04). 

You will need to get a copy of sassc, most likely through a tool like `npm` since it isn't packaged in xenial. All of the other build-dependencies can be found in the repositories.

**Comment by rdkumarj** [comment]
Hi @isantop 

Thanks for the reply. Are you going to support Ubuntu 16.04 in future? if not are you going to support Future versions of Ubuntu?

Thanks.

**Comment by sayakbiswas** [comment]
Hi,

Thanks, I was able to compile this today as well. Looks great. I am also interested in knowing if Ubuntu 16.04 would be supported in the future or not. Although @rdkumarj  I am pretty sure future Ubuntu versions would be supported since they plan to ship Ubuntu with this theme in their PC lineup.

Thanks

**Comment by isantop** [comment]
There will definitely be support for future Ubuntu versions. Going back to 16.04 is still on the table, but not a high priority right now.
