### ISSUE TITLE
The titlebar on Terminal and few other apps is too short.

### ISSUE THREAD

**Issue by tusharkant15** [system76/pop-gtk-theme#60]
**NOTE: Before reporting a bug, please check whether it also occurs with other themes.**
> If the bug also occurs with other themes (especially upstream default theme),
it is very likely an upstream issue.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Gtk+ 3.0 version - (run ```apt policy libgtk-3-0```)
 * Desktop environment - 
 * Pop version - (run ```apt policy pop-gtk-theme```)
 ```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful

apt policy libgtk-3-0
libgtk-3-0:
  Installed: 3.22.21-0ubuntu1
  Candidate: 3.22.21-0ubuntu1
  Version table:
 *** 3.22.21-0ubuntu1 500
        500 http://in.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status


apt policy pop-gtk-theme
pop-gtk-theme:
  Installed: 2.1.2.1
  Candidate: 2.1.2.1
  Version table:
 *** 2.1.2.1 500
        500 http://ppa.launchpad.net/system76/pop/ubuntu artful/main amd64 Packages
        500 http://ppa.launchpad.net/system76/pop/ubuntu artful/main i386 Packages
        100 /var/lib/dpkg/status

```
**Related Application and/or Shell theming (or name of widget)**
Issue occurs in Terminal and system updater (Only terminal screenshot provided)

**Actual issue**
The titlebar is cutoff in the bottom.

**Steps to reproduce**
Launch terminal.

**Expected behavior**
The titlebar should look like this (screenshot from my desktop)
![screenshot from 2017-10-16 13-37-26](https://user-images.githubusercontent.com/3088331/31601391-528ca48c-b277-11e7-8e6d-2118cdc31979.png)

Instead looks like this
![screenshot from 2017-10-16 13-29-05](https://user-images.githubusercontent.com/3088331/31601421-67ab0a98-b277-11e7-9363-cee7a95355cf.png)

**Behavior in Adwaita**
![screenshot from 2017-10-16 13-28-33](https://user-images.githubusercontent.com/3088331/31601424-6e9925e2-b277-11e7-97ea-402ab416c558.png)

**Behaviour in Arc**
![screenshot from 2017-10-16 13-28-45](https://user-images.githubusercontent.com/3088331/31601437-7d47f398-b277-11e7-992e-be381bee389d.png)

**Other Note (feature-request, question, etc...)**
This issue does not occur on my desktop with nvidia card. Maybe and intel or wayland issue? I have also set my font scaling to 1.25 in Tweaks so could be that as well.

**Comment by isantop** [comment]
This was caused by our previous addition for support of CSD titlebars in applications like GNOME terminal.

```.csd .default-decoration {
  padding-top: 0;
  padding-bottom: 0;

  button {
    margin-top: 0;
    margin-bottom: 0;
  }

  .title {
    min-height: 24px;
    padding-top: 6px;
    padding-bottom: 6px;
  }
}
```
This sets Default decorations to use no padding on any widgets within the titlebar, which is required for reducing the size of titlebars which are drawn using CSD headerbar widgets but aren't intended to be full-size headerbar style. This doesn't affect X sessions because apps which don't use CSD on X have their titlebars drawn directly by the window manager, and are style elsewhere. However, in Wayland, all windows use CSD, and thus are caught by this selector. However, because these apps have no titlebar-specific styling (since they aren't intending to draw the titlebar at all). The 24px min-height is too small for the titlebar to fit its contents fully, thus the weird padding and mini-titlebars.
